In [16]:
import pandas as pd
import sklearn
n='TargetDataBasecsv.csv'
m='completedclient.csv'
df1=pd.read_csv(m)
df=pd.read_csv(n)


In [17]:
ym=df.columns.values.tolist()
ym


['Acct_id',
 'Acct_UIDNo.',
 'Acct_FName',
 'Acct_MName',
 'Acct_LName',
 'Acct_Addr1',
 'Acct_Addr2',
 'Acct_City',
 'Acct_State',
 'Acct_phone',
 'Acct_email',
 'Acct_DOB',
 'Acct_Gender']

In [18]:
ym1=df1.columns.values.tolist()
ym1

['client_id',
 'sex',
 'fulldate',
 'day',
 'month',
 'year',
 'age',
 'social',
 'first',
 'middle',
 'last',
 'phone',
 'email',
 'address_1',
 'address_2',
 'city',
 'state',
 'zipcode',
 'district_id']

In [5]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()

In [6]:
df_final=Le.fit_transform(ym)
df_final


array([11,  9,  4,  7,  6,  0,  1,  2,  8, 12, 10,  3,  5], dtype=int64)

In [7]:
df1_final=Le.fit_transform(ym1)
df1_final

array([ 4, 14,  9,  5, 12, 17,  2, 15,  8, 11, 10, 13,  7,  0,  1,  3, 16,
       18,  6], dtype=int64)

In [8]:
dfd = pd.DataFrame(df_final, columns=['Target Table'])
ym= pd.DataFrame(ym,columns=['Target name'])
dfd=pd.merge(ym,dfd,right_index=True, left_index=True)
dfd

Target name  Target Table
0       Acct_id            11
1   Acct_UIDNo.             9
2    Acct_FName             4
3    Acct_MName             7
4    Acct_LName             6
5    Acct_Addr1             0
6    Acct_Addr2             1
7     Acct_City             2
8    Acct_State             8
9    Acct_phone            12
10   Acct_email            10
11     Acct_DOB             3
12  Acct_Gender             5

In [9]:
df1d = pd.DataFrame(df1_final, columns=['Test Table'])
ym1= pd.DataFrame(ym1,columns=['Test name'])
df1d=pd.merge(ym1,df1d,right_index=True, left_index=True)
df1d

Test name  Test Table
0     client_id           4
1           sex          14
2      fulldate           9
3           day           5
4         month          12
5          year          17
6           age           2
7        social          15
8         first           8
9        middle          11
10         last          10
11        phone          13
12        email           7
13    address_1           0
14    address_2           1
15         city           3
16        state          16
17      zipcode          18
18  district_id           6

In [10]:
df_final=df_final.tolist()
df_final


[11, 9, 4, 7, 6, 0, 1, 2, 8, 12, 10, 3, 5]

In [11]:
df1_final=df1_final.tolist()
df1_final

[4, 14, 9, 5, 12, 17, 2, 15, 8, 11, 10, 13, 7, 0, 1, 3, 16, 18, 6]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances
cosine_similarity([df_final],[df1_final])

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 13 while Y.shape[1] == 19

In [13]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [14]:
enc_df = pd.DataFrame(enc.fit_transform(dfd[['Target Table']]).toarray())

In [15]:
dfd = dfd.join(enc_df)

dfd

Target name  Target Table    0    1    2    3    4    5    6    7    8  \
0       Acct_id            11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1   Acct_UIDNo.             9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    Acct_FName             4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
3    Acct_MName             7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
4    Acct_LName             6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
5    Acct_Addr1             0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6    Acct_Addr2             1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7     Acct_City             2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
8    Acct_State             8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
9    Acct_phone            12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
10   Acct_email            10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
11     Acct_DOB             3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
12  Acct_Gender             5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   

      9   10   11   12  
0   0.0  0.0  1.0  0.0  
1   1.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  0.0  
5   0.0  0.0  0.0  0.0  
6   0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  
9   0.0  0.0  0.0  1.0  
10  0.0  1.0  0.0  0.0  
11  0.0  0.0  0.0  0.0  
12  0.0  0.0  0.0  0.0

In [16]:
dfd=dfd.drop(columns=['Target name'],axis=1)
dfd

Target Table    0    1    2    3    4    5    6    7    8    9   10   11  \
0             11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1              9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
2              4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3              7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
4              6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
5              0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6              1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7              2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8              8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
9             12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
10            10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
11             3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
12             5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   

     12  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  
5   0.0  
6   0.0  
7   0.0  
8   0.0  
9   1.0  
10  0.0  
11  0.0  
12  0.0

In [23]:
enc_df1 = pd.DataFrame(enc.fit_transform(df1d[['Test Table']]).toarray())
enc_df1

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
3   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
6   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
14  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
18  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     15   16   17   18  
0   0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  0.0  
5   0.0  0.0  1.0  0.0  
6   0.0  0.0  0.0  0.0  
7   1.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  
9   0.0  0.0  0.0  0.0  
10  0.0  0.0  0.0  0.0  
11  0.0  0.0  0.0  0.0  
12  0.0  0.0  0.0  0.0  
13  0.0  0.0  0.0  0.0  
14  0.0  0.0  0.0  0.0  
15  0.0  0.0  0.0  0.0  
16  0.0  1.0  0.0  0.0  
17  0.0  0.0  0.0  1.0  
18  0.0  0.0  0.0  0.0

In [18]:
df1d = df1d.join(enc_df1)
df1d

Test name  Test Table    0    1    2    3    4    5    6    7  ...    9  \
0     client_id           4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   
1           sex          14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
2      fulldate           9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0   
3           day           5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0   
4         month          12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
5          year          17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
6           age           2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
7        social          15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
8         first           8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
9        middle          11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
10         last          10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
11        phone          13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
12        email           7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0   
13    address_1           0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
14    address_2           1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
15         city           3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0   
16        state          16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
17      zipcode          18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
18  district_id           6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   

     10   11   12   13   14   15   16   17   18  
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
11  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[19 rows x 21 columns]

In [22]:
df1d.drop(columns=['Test name'],axis=1)
df1d

Test name  Test Table    0    1    2    3    4    5    6    7  ...    9  \
0     client_id           4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   
1           sex          14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
2      fulldate           9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0   
3           day           5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0   
4         month          12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
5          year          17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
6           age           2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
7        social          15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
8         first           8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
9        middle          11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
10         last          10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
11        phone          13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
12        email           7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0   
13    address_1           0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
14    address_2           1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
15         city           3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0   
16        state          16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
17      zipcode          18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
18  district_id           6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   

     10   11   12   13   14   15   16   17   18  
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
11  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[19 rows x 21 columns]

In [20]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
vec.fit_transform(n).toarray()

AttributeError: 'str' object has no attribute 'items'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [120]:
vectorizer = CountVectorizer()

In [121]:
X = vectorizer.fit_transform(ym)

In [122]:
X

<13x13 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [123]:
X.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [128]:
Y = vectorizer.fit_transform(ym1)

In [129]:
Y

<19x19 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [130]:
Y.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0,

In [134]:
sklearn.metrics.pairwise.cosine_distances(X,Y)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 13 while Y.shape[1] == 19

In [24]:
pip install segmentation-models

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
import tensorflow


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer()

In [22]:
X = vectorizer.fit_transform(ym)

In [23]:
print(vectorizer.get_feature_names())

['acct_addr1', 'acct_addr2', 'acct_city', 'acct_dob', 'acct_email', 'acct_fname', 'acct_gender', 'acct_id', 'acct_lname', 'acct_mname', 'acct_phone', 'acct_state', 'acct_uidno']


In [24]:
print(X.shape)

(13, 13)


In [27]:
X.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [12]:
pip install keras

  Using cached PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
Note: you may need to restart the kernel to use updated packages.


In [28]:
from tensorflow.keras.preprocessing.text import one_hot

In [29]:
voc_size=10000

In [30]:
onehot_repr=[one_hot(words,voc_size)for words in ym] 
print(onehot_repr)

[[4307, 8155], [4307, 4147], [4307, 1425], [4307, 741], [4307, 5615], [4307, 9123], [4307, 5719], [4307, 2219], [4307, 1648], [4307, 7214], [4307, 355], [4307, 1316], [4307, 5097]]


In [31]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
sent_length=2
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4307 8155]
 [4307 4147]
 [4307 1425]
 [4307  741]
 [4307 5615]
 [4307 9123]
 [4307 5719]
 [4307 2219]
 [4307 1648]
 [4307 7214]
 [4307  355]
 [4307 1316]
 [4307 5097]]


In [34]:
dim=10

In [35]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 2, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [47]:
df_final=model.predict(embedded_docs)
print(df_final)

[[[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.04475224  0.00354111  0.0314566  -0.03939313 -0.03765974
    0.00128193 -0.00927861 -0.02903291 -0.04850748 -0.04003046]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.01575165 -0.00300013  0.00647368  0.01958651  0.00692167
   -0.00864118 -0.03192033  0.03577782  0.0443342  -0.02415438]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.02499528  0.00997872  0.03277255  0.02308711 -0.03653344
   -0.02845057 -0.0314128   0.03120086 -0.00882689  0.01561325]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.03892717  0.04582204 -0.03350043 -0.02023629  0.03114953
    0.01247931 -0.02132297 -0.00857488 -0.

In [37]:
embedded_docs[0]

array([4307, 8155])

In [40]:
print(model.predict(embedded_docs)[0])

[[ 0.04860908 -0.04942579 -0.02701199 -0.02313532 -0.02505285  0.04244756
   0.04994459  0.02407591  0.01944577 -0.00658996]
 [ 0.03268505  0.04199691  0.04895972  0.01470277  0.04541311 -0.00182579
  -0.02423388  0.02329422 -0.01014798  0.008566  ]]


In [42]:
onehot_repr1=[one_hot(words,voc_size)for words in ym1] 
print(onehot_repr1)

[[9220, 8155], [2224], [2412], [409], [3339], [6003], [3897], [2761], [4707], [5978], [3178], [7214], [355], [3816, 2166], [3816, 8711], [2219], [1648], [501], [6243, 8155]]


In [43]:
sent_length=2
embedded_docs1=pad_sequences(onehot_repr1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[9220 8155]
 [   0 2224]
 [   0 2412]
 [   0  409]
 [   0 3339]
 [   0 6003]
 [   0 3897]
 [   0 2761]
 [   0 4707]
 [   0 5978]
 [   0 3178]
 [   0 7214]
 [   0  355]
 [3816 2166]
 [3816 8711]
 [   0 2219]
 [   0 1648]
 [   0  501]
 [6243 8155]]


In [44]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [48]:
df_final1=model.predict(embedded_docs1)
df_final1

array([[[ 0.0234515 ,  0.00030862,  0.0168777 ,  0.00742185,
          0.03254129, -0.03058815, -0.01384569, -0.02054203,
          0.01623074,  0.04514182],
        [ 0.04475224,  0.00354111,  0.0314566 , -0.03939313,
         -0.03765974,  0.00128193, -0.00927861, -0.02903291,
         -0.04850748, -0.04003046]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.00408828,  0.00422912,  0.04966784,  0.01093168,
         -0.03776255, -0.0094367 , -0.0010892 ,  0.01323842,
         -0.0132582 , -0.02116332]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.04243771,  0.04103725,  0.0175286 ,  0.03982917,
         -0.04186244,  0.00060339, -0.00439788,  0.0052686 ,
          0.03604833,  0.04614092]],

       [[-0.03833247,  0.00802621, -0.04797062

In [50]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances
cosine_similarity(embedded_docs1,embedded_docs)

array([[0.93564668, 0.99910571, 0.91923638, 0.85053097, 0.98156901,
        0.9188918 , 0.97984105, 0.96929717, 0.93634202, 0.95282618,
        0.80093466, 0.90994708, 0.9895018 ],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880

In [51]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(embedded_docs1,embedded_docs)

array([[4913.        , 6340.47577079, 8332.49476447, 8894.09719983,
        5530.74759865, 5007.45374417, 5483.76376223, 7705.43087699,
        8153.44209521, 5002.30446894, 9218.32788525, 8420.77728004,
        5786.96232924],
       [7329.87107663, 4716.79743046, 4380.48513295, 4555.1660782 ,
        5481.70867522, 8133.04678457, 5546.64529243, 4307.00290225,
        4345.34521068, 6591.68787186, 4695.04100089, 4401.67161428,
        5177.29446719],
       [7178.60000279, 4643.32574778, 4418.64436225, 4619.79328542,
        5367.44427079, 7974.19400316, 5430.14714349, 4311.32207101,
        4374.23650481, 6450.53896973, 4772.99675257, 4444.26203098,
        5075.37919766],
       [8862.88694501, 5702.88462096, 4425.21242428, 4319.77696183,
        6756.67706791, 9720.29037632, 6837.13017281, 4671.86782775,
        4481.6704475 , 8053.46347853, 4307.33850539, 4401.46543778,
        6366.12857237],
       [6460.96780676, 4382.13566654, 4713.13536831, 5029.89592338,
        4871.3884057